/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  boolean,
  numeric,
  jsonb,
  type AnyPgColumn,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "editor",
  "author",
  "viewer",
]);
export const enum_posts_status = pgEnum("enum_posts_status", [
  "draft",
  "review",
  "scheduled",
  "published",
  "archived",
]);
export const enum__posts_v_version_status = pgEnum(
  "enum__posts_v_version_status",
  ["draft", "review", "scheduled", "published", "archived"],
);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum_redirects_status_code = pgEnum("enum_redirects_status_code", [
  "301",
  "302",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    role: enum_users_role("role").notNull().default("author"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    isActive: boolean("is_active").default(true),
    lastLoginAt: timestamp("last_login_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_avatar_idx").on(columns.avatar),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const authors = pgTable(
  "authors",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    bio: varchar("bio"),
    avatar: integer("avatar_id").references(() => media.id, {
      onDelete: "set null",
    }),
    email: varchar("email"),
    socialLinks_facebook: varchar("social_links_facebook"),
    socialLinks_twitter: varchar("social_links_twitter"),
    socialLinks_instagram: varchar("social_links_instagram"),
    user: integer("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("authors_slug_idx").on(columns.slug),
    index("authors_avatar_idx").on(columns.avatar),
    index("authors_user_idx").on(columns.user),
    index("authors_updated_at_idx").on(columns.updatedAt),
    index("authors_created_at_idx").on(columns.createdAt),
  ],
);

export const posts = pgTable(
  "posts",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    excerpt: varchar("excerpt"),
    content: jsonb("content"),
    featuredImage: integer("featured_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    category: integer("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    author: integer("author_id").references(() => authors.id, {
      onDelete: "set null",
    }),
    status: enum_posts_status("status").default("draft"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    scheduledAt: timestamp("scheduled_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    seoTitle: varchar("seo_title"),
    seoDescription: varchar("seo_description"),
    canonicalUrl: varchar("canonical_url"),
    ogImage: integer("og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    isFeatured: boolean("is_featured").default(false),
    isBreakingNews: boolean("is_breaking_news").default(false),
    allowIndex: boolean("allow_index").default(true),
    sourceName: varchar("source_name"),
    sourceUrl: varchar("source_url"),
    readingTime: numeric("reading_time", { mode: "number" }),
    views: numeric("views", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_posts_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("posts_slug_idx").on(columns.slug),
    index("posts_featured_image_idx").on(columns.featuredImage),
    index("posts_category_idx").on(columns.category),
    index("posts_author_idx").on(columns.author),
    index("posts_og_image_idx").on(columns.ogImage),
    index("posts_updated_at_idx").on(columns.updatedAt),
    index("posts_created_at_idx").on(columns.createdAt),
    index("posts__status_idx").on(columns._status),
  ],
);

export const posts_rels = pgTable(
  "posts_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    tagsID: integer("tags_id"),
  },
  (columns) => [
    index("posts_rels_order_idx").on(columns.order),
    index("posts_rels_parent_idx").on(columns.parent),
    index("posts_rels_path_idx").on(columns.path),
    index("posts_rels_tags_id_idx").on(columns.tagsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [posts.id],
      name: "posts_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "posts_rels_tags_fk",
    }).onDelete("cascade"),
  ],
);

export const _posts_v = pgTable(
  "_posts_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => posts.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_excerpt: varchar("version_excerpt"),
    version_content: jsonb("version_content"),
    version_featuredImage: integer("version_featured_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_category: integer("version_category_id").references(
      () => categories.id,
      {
        onDelete: "set null",
      },
    ),
    version_author: integer("version_author_id").references(() => authors.id, {
      onDelete: "set null",
    }),
    version_status:
      enum__posts_v_version_status("version_status").default("draft"),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_scheduledAt: timestamp("version_scheduled_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_seoTitle: varchar("version_seo_title"),
    version_seoDescription: varchar("version_seo_description"),
    version_canonicalUrl: varchar("version_canonical_url"),
    version_ogImage: integer("version_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_isFeatured: boolean("version_is_featured").default(false),
    version_isBreakingNews: boolean("version_is_breaking_news").default(false),
    version_allowIndex: boolean("version_allow_index").default(true),
    version_sourceName: varchar("version_source_name"),
    version_sourceUrl: varchar("version_source_url"),
    version_readingTime: numeric("version_reading_time", { mode: "number" }),
    version_views: numeric("version_views", { mode: "number" }).default(0),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__posts_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_posts_v_parent_idx").on(columns.parent),
    index("_posts_v_version_version_slug_idx").on(columns.version_slug),
    index("_posts_v_version_version_featured_image_idx").on(
      columns.version_featuredImage,
    ),
    index("_posts_v_version_version_category_idx").on(columns.version_category),
    index("_posts_v_version_version_author_idx").on(columns.version_author),
    index("_posts_v_version_version_og_image_idx").on(columns.version_ogImage),
    index("_posts_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_posts_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_posts_v_version_version__status_idx").on(columns.version__status),
    index("_posts_v_created_at_idx").on(columns.createdAt),
    index("_posts_v_updated_at_idx").on(columns.updatedAt),
    index("_posts_v_latest_idx").on(columns.latest),
    index("_posts_v_autosave_idx").on(columns.autosave),
  ],
);

export const _posts_v_rels = pgTable(
  "_posts_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    tagsID: integer("tags_id"),
  },
  (columns) => [
    index("_posts_v_rels_order_idx").on(columns.order),
    index("_posts_v_rels_parent_idx").on(columns.parent),
    index("_posts_v_rels_path_idx").on(columns.path),
    index("_posts_v_rels_tags_id_idx").on(columns.tagsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_posts_v.id],
      name: "_posts_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "_posts_v_rels_tags_fk",
    }).onDelete("cascade"),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    parent: integer("parent_id").references((): AnyPgColumn => categories.id, {
      onDelete: "set null",
    }),
    seoTitle: varchar("seo_title"),
    seoDescription: varchar("seo_description"),
    order: numeric("order", { mode: "number" }).default(0),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_parent_idx").on(columns.parent),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const tags = pgTable(
  "tags",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("tags_slug_idx").on(columns.slug),
    index("tags_updated_at_idx").on(columns.updatedAt),
    index("tags_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    credit: varchar("credit"),
    folder: varchar("folder").default("/"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
    sizes_og_url: varchar("sizes_og_url"),
    sizes_og_width: numeric("sizes_og_width", { mode: "number" }),
    sizes_og_height: numeric("sizes_og_height", { mode: "number" }),
    sizes_og_mimeType: varchar("sizes_og_mime_type"),
    sizes_og_filesize: numeric("sizes_og_filesize", { mode: "number" }),
    sizes_og_filename: varchar("sizes_og_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
    index("media_sizes_og_sizes_og_filename_idx").on(columns.sizes_og_filename),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    content: jsonb("content").notNull(),
    seoTitle: varchar("seo_title"),
    seoDescription: varchar("seo_description"),
    status: enum_pages_status("status").default("draft"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
  ],
);

export const redirects = pgTable(
  "redirects",
  {
    id: serial("id").primaryKey(),
    from: varchar("from").notNull(),
    to: varchar("to").notNull(),
    statusCode: enum_redirects_status_code("status_code")
      .notNull()
      .default("301"),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("redirects_updated_at_idx").on(columns.updatedAt),
    index("redirects_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    authorsID: integer("authors_id"),
    postsID: integer("posts_id"),
    categoriesID: integer("categories_id"),
    tagsID: integer("tags_id"),
    mediaID: integer("media_id"),
    pagesID: integer("pages_id"),
    redirectsID: integer("redirects_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_authors_id_idx").on(columns.authorsID),
    index("payload_locked_documents_rels_posts_id_idx").on(columns.postsID),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_tags_id_idx").on(columns.tagsID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_redirects_id_idx").on(
      columns.redirectsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["authorsID"]],
      foreignColumns: [authors.id],
      name: "payload_locked_documents_rels_authors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["postsID"]],
      foreignColumns: [posts.id],
      name: "payload_locked_documents_rels_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "payload_locked_documents_rels_tags_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["redirectsID"]],
      foreignColumns: [redirects.id],
      name: "payload_locked_documents_rels_redirects_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const settings = pgTable(
  "settings",
  {
    id: serial("id").primaryKey(),
    siteName: varchar("site_name").default("PorosMadura"),
    siteDescription: varchar("site_description"),
    tagline: varchar("tagline").default("Berita Tepat, Fakta Kuat"),
    siteUrl: varchar("site_url"),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    logoDark: integer("logo_dark_id").references(() => media.id, {
      onDelete: "set null",
    }),
    favicon: integer("favicon_id").references(() => media.id, {
      onDelete: "set null",
    }),
    defaultOgImage: integer("default_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    contactEmail: varchar("contact_email"),
    socialLinks_facebook: varchar("social_links_facebook"),
    socialLinks_twitter: varchar("social_links_twitter"),
    socialLinks_instagram: varchar("social_links_instagram"),
    socialLinks_youtube: varchar("social_links_youtube"),
    defaultSeoTitle: varchar("default_seo_title").default("PorosMadura"),
    defaultSeoDescription: varchar("default_seo_description").default(
      "Berita Tepat, Fakta Kuat",
    ),
    googleAnalyticsId: varchar("google_analytics_id"),
    rssTitle: varchar("rss_title").default("PorosMadura"),
    rssDescription: varchar("rss_description").default(
      "Berita Tepat, Fakta Kuat",
    ),
    newsPublicationName: varchar("news_publication_name").default(
      "PorosMadura",
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("settings_logo_idx").on(columns.logo),
    index("settings_logo_dark_idx").on(columns.logoDark),
    index("settings_favicon_idx").on(columns.favicon),
    index("settings_default_og_image_idx").on(columns.defaultOgImage),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_authors = relations(authors, ({ one }) => ({
  avatar: one(media, {
    fields: [authors.avatar],
    references: [media.id],
    relationName: "avatar",
  }),
  user: one(users, {
    fields: [authors.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: "_rels",
  }),
  tagsID: one(tags, {
    fields: [posts_rels.tagsID],
    references: [tags.id],
    relationName: "tags",
  }),
}));
export const relations_posts = relations(posts, ({ one, many }) => ({
  featuredImage: one(media, {
    fields: [posts.featuredImage],
    references: [media.id],
    relationName: "featuredImage",
  }),
  category: one(categories, {
    fields: [posts.category],
    references: [categories.id],
    relationName: "category",
  }),
  author: one(authors, {
    fields: [posts.author],
    references: [authors.id],
    relationName: "author",
  }),
  ogImage: one(media, {
    fields: [posts.ogImage],
    references: [media.id],
    relationName: "ogImage",
  }),
  _rels: many(posts_rels, {
    relationName: "_rels",
  }),
}));
export const relations__posts_v_rels = relations(_posts_v_rels, ({ one }) => ({
  parent: one(_posts_v, {
    fields: [_posts_v_rels.parent],
    references: [_posts_v.id],
    relationName: "_rels",
  }),
  tagsID: one(tags, {
    fields: [_posts_v_rels.tagsID],
    references: [tags.id],
    relationName: "tags",
  }),
}));
export const relations__posts_v = relations(_posts_v, ({ one, many }) => ({
  parent: one(posts, {
    fields: [_posts_v.parent],
    references: [posts.id],
    relationName: "parent",
  }),
  version_featuredImage: one(media, {
    fields: [_posts_v.version_featuredImage],
    references: [media.id],
    relationName: "version_featuredImage",
  }),
  version_category: one(categories, {
    fields: [_posts_v.version_category],
    references: [categories.id],
    relationName: "version_category",
  }),
  version_author: one(authors, {
    fields: [_posts_v.version_author],
    references: [authors.id],
    relationName: "version_author",
  }),
  version_ogImage: one(media, {
    fields: [_posts_v.version_ogImage],
    references: [media.id],
    relationName: "version_ogImage",
  }),
  _rels: many(_posts_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_categories = relations(categories, ({ one }) => ({
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: "parent",
  }),
}));
export const relations_tags = relations(tags, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_pages = relations(pages, () => ({}));
export const relations_redirects = relations(redirects, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: "authors",
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: "posts",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: "tags",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    redirectsID: one(redirects, {
      fields: [payload_locked_documents_rels.redirectsID],
      references: [redirects.id],
      relationName: "redirects",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_settings = relations(settings, ({ one }) => ({
  logo: one(media, {
    fields: [settings.logo],
    references: [media.id],
    relationName: "logo",
  }),
  logoDark: one(media, {
    fields: [settings.logoDark],
    references: [media.id],
    relationName: "logoDark",
  }),
  favicon: one(media, {
    fields: [settings.favicon],
    references: [media.id],
    relationName: "favicon",
  }),
  defaultOgImage: one(media, {
    fields: [settings.defaultOgImage],
    references: [media.id],
    relationName: "defaultOgImage",
  }),
}));

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_posts_status: typeof enum_posts_status;
  enum__posts_v_version_status: typeof enum__posts_v_version_status;
  enum_pages_status: typeof enum_pages_status;
  enum_redirects_status_code: typeof enum_redirects_status_code;
  users_sessions: typeof users_sessions;
  users: typeof users;
  authors: typeof authors;
  posts: typeof posts;
  posts_rels: typeof posts_rels;
  _posts_v: typeof _posts_v;
  _posts_v_rels: typeof _posts_v_rels;
  categories: typeof categories;
  tags: typeof tags;
  media: typeof media;
  pages: typeof pages;
  redirects: typeof redirects;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  settings: typeof settings;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_authors: typeof relations_authors;
  relations_posts_rels: typeof relations_posts_rels;
  relations_posts: typeof relations_posts;
  relations__posts_v_rels: typeof relations__posts_v_rels;
  relations__posts_v: typeof relations__posts_v;
  relations_categories: typeof relations_categories;
  relations_tags: typeof relations_tags;
  relations_media: typeof relations_media;
  relations_pages: typeof relations_pages;
  relations_redirects: typeof relations_redirects;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_settings: typeof relations_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
